server:
  port: 9910
  servlet:
    context-path: /device

spring:
  profiles:
    active: dev


---
spring:
  application:
    name: DeviceManagerServer
  profiles: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/earth?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&
    username: root
    password:
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    # open PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,logback

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 8
    timeout: 3000ms
    lettuce:
      pool:
        min-idle: 3
        max-active: 18
        max-wait: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
#    如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#    如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    field-strategy: 0
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    配置null对应的JDBC类型，Oracle数据库必须配置此项
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl










