server:
  port: 9910
  servlet:
    context-path: /device

spring:
  application:
    name: DeviceManagerServer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.0.0.1:3306/earth?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:


  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 8
    timeout: 3000ms
    lettuce:
      pool:
        min-idle: 3
        max-active: 18
        max-wait: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




